//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BXH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOICHOI
    {
        public NGUOICHOI()
        {
            this.BXH = new HashSet<BXH>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<BXH> BXH { get; set; }
    }
}
